version: '3'

services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: company_management_development
    volumes:
      - db:/var/lib/postgres/data

volumes:
  db:
